### ISSUE TITLE
Can not save checkpoint

### ISSUE THREAD

**Issue by mohsinlakhani** [rail-berkeley/softlearning#104]
Hi. Thanks for the repo. I have been using SAC with HER on a custom environment and robot. I had just recently moved to the latest versions of the repo and all packages and tested with HER. Now when the algo tries to create a checkpoint I get this error. 

`File "/home/MohsinLakhani/anaconda2/envs/thesis/lib/python3.7/site-packages/ray/tune/trainable.py", line 241, in save
    checkpoint = self._save(checkpoint_dir)
  File "/home/MohsinLakhani/thesis/softlearning/examples/development/main.py", line 159, in _save
    pickle.dump(self.picklables, f)
TypeError: can't pickle _thread.RLock objects`

Any help would be appreciated. I have never faced this error earlier, even though I have been using the repo almost since it was created. P.S this is my 2nd ever git issue so if anything is wrong feel free to point out.

**Comment by mbed92** [comment]
I think that everything is OK with your post. In my case, I'm getting an error ```self.ptr cannot be converted to a Python object for pickling``` whenever the checkpoint is created (checkpoint is not created anymore). I'm also working on my custom environment, but it never happened before. This is my running command:
```bash
softlearning run_example_debug examples.development     \
                --universe=gym     \
                --domain=ManipulatorEnvRopeFolding     \
                --task=v0   \
                --exp-name="manipulation-sin_wave"     \
                --checkpoint-frequency=10    \
                --algorithm="SAC"   \
                --cpus=4
```

**Comment by mbed92** [comment]
@mohsinlakhani didn't you forget to add ```self._Serializable__initialize(locals())``` in the ```__init__()``` method of your custom environment? That worked for me.

**Comment by mohsinlakhani** [comment]
@mbed92 Thanks. That solved the issue. This was included in the adapters at first so I didn't include it in my custom environment.
