### ISSUE TITLE
A fatal error occurred

### ISSUE THREAD

**Issue by Max-918** [rail-berkeley/softlearning#129]
When I want to train the angle，a fatal error occurred.
![微信图片_20200325114619](https://user-images.githubusercontent.com/55472156/77499870-475e5f80-6e8e-11ea-9abb-0e352ee3babe.jpg)

**Comment by hartikainen** [comment]
It seems like your mujoco compilation fails, but given that the output is cut off it's hard to say what exactly goes wrong. Have you [installed mujoco](https://github.com/openai/mujoco-py#install-mujoco) and added the mujoco key into the mujoco installation folder?

Btw, in the future, it might be nicer to post a plain text output (i.e. copy-pasting it from terminal and using the [markdown formatting](https://guides.github.com/features/mastering-markdown/)) of the error. That makes the error is much more readable and easily searchable, which might speed up getting a solution to the problem.

Happy to help you further if you provide a full output of the error.

**Comment by hartikainen** [comment]
Seems like this is not an issue in softlearning so I'll close this for now. Please let me know if the issue still persists!
