### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by kapsl** [rail-berkeley/softlearning#130]
Hi,
today i tested the latest master branch and found following issues:

- if in the program args --algorithm is not set, the program starts, but a strange error is shown
- I had problems when tune tried to store hparams 
- Problems when storing yaml: TypeError: can't pickle weakref objects

**Comment by hartikainen** [comment]
Hey @kapsl! Thanks for reporting these. For the first two, I've actually hit the same issues and have a code ready to fix those. Let me open a PR and merge it to master in a bit.

For the final point, could you provide a bit more context on that? I haven't seen an issue like that before.

**Comment by kapsl** [comment]
Actually i'm still investigating. It seems like it works for the normal variant. But I tried adding a convnet preprocessor and there the problem arises, will report, when i now more...

**Comment by hartikainen** [comment]
@kapsl I merged fixes for the first two problems. Please open a new issue for the third problem if it still persists.
