### ISSUE TITLE
Incompatible with ray 1.2.0

### ISSUE THREAD

**Issue by xanderdunn** [rail-berkeley/softlearning#169]
setup.py lists its ray dependency as `ray[tune]>=1.0.0`

Currently this installs ray 1.2.0, which gives this error:
```
  File "/home/xander/dev/softlearning/softlearning/scripts/console_scripts.py", line 26, in <module>
    from examples.instrument import (
  File "/home/xander/dev/softlearning/examples/instrument.py", line 25, in <module>
    from ray.autoscaler.commands import exec_cluster
ModuleNotFoundError: No module named 'ray.autoscaler.commands'
```

Forcing the installation of ray 1.0.0 solves this: `pip install ray[tune]==1.0.0`.

Might want to peg the ray dependency version to something lower than 1.2. I didn't try if 1.1 works.

**Comment by hartikainen** [comment]
Thanks for reporting this! I just pushed a fix for this in #171. The ray requirement is pinned in `requirements.txt` but not in `setup.py` to allow some flexibility with the versions.
