### ISSUE TITLE
Support for SQL

### ISSUE THREAD

**Issue by bohan-zhang** [rail-berkeley/softlearning#20]
Currently all code in `experiments/` only supports `SAC`, but not `SQL`. Do you have any plans on adding support for `SQL` soon? @hartikainen @haarnoja

**Comment by hartikainen** [comment]
We're planning to fix and test the SQL experiments sometime in the near future. That's not a very high priority for me right now though since most of our current experiments are run using SAC, and we also have an old (working) version implemented at https://github.com/haarnoja/softqlearning. If you want to run SQL immediately, I would recommend checking out that repo.

Also, if you're interested in contributing the fixes to make SQL run again, that would be much appreciated! There shouldn't be too many changed required to make it work, and I would be happy to answer any questions you might have while doing it.

**Comment by bohan-zhang** [comment]
@hartikainen Thank you so much for getting back to me so quickly! I tried to make SQL run again on Mac by migrating SQL's dependency of `rllab` to `garage` here: http://github.com/bohan-zhang/softqlearning. It's working but compared to this repository, I feel it's a better idea to use `softlearning`, as it has fewer dependencies.

It's my intention to contribute to repository, and I have a few questions:
- Should I fork this repository and merge to upstream or I can just create a branch and contribute to this repo directly?
- Do you have any pointers on the files I should modify to make SQL run again? I'm looking at https://github.com/rail-berkeley/softlearning/blob/master/examples/utils.py and https://github.com/rail-berkeley/softlearning/blob/master/examples/multi_goal.py

Also, I look forward to working with you to make SQL work again!

**Comment by hartikainen** [comment]
Nice, I had totally missed the PR you made to softqlearning repo. Much appreciated!

> Should I fork this repository and merge to upstream or I can just create a branch and contribute to this repo directly?

Yeah, I would say create a fork and then create a PR through that. That's the easiest way to handle things.

> Do you have any pointers on the files I should modify to make SQL run again?

Here's a rough outline of what I would do:
1. Move the `multi_goal.py` example in its own `multi_goal` module, just like we currently do for the development example. I.e. create `multi_goal/variants.py`, `multi_goal/main.py`, `multi_goal/__init__.py`
2. Then change the multigoal main function

https://github.com/rail-berkeley/softlearning/blob/28d3cb2c31496e6f548896816b6e1da0a5010031/examples/multi_goal.py#L75

to have two different variant configurations based on, say, `args.algorithm`, in a same way we do for images in the development main currently: https://github.com/rail-berkeley/softlearning/blob/cbe3855e5c5a30921855d424882904b27161ac83/examples/development/main.py#L192-L198

3. In `examples/utils.py` add the `args.algorithm` option to [arg parser](https://github.com/rail-berkeley/softlearning/blob/b375512894d331eb1cbcb0f9f15ae0b6120a3e14/examples/utils.py#L157-L160).

4. In `multi_goal/variants.py` implement variants for SQL, e.g. `get_variants_SQL` and use that in the main.

5. The [SQL algorithm](https://github.com/rail-berkeley/softlearning/blob/28d3cb2c31496e6f548896816b6e1da0a5010031/softlearning/algorithms/sql.py) shouldn't have any bigger issues, but I'm pretty sure some minor things will need to be fixed. These should be easy to debug using the multi_goal example.

6. Once `multi_goal` works, do part 3) for `examples/development/variants.py`, i.e. add `get_variants_SQL`. At this point everything should be runnable with SQL :)


Let me know if you have any other questions. I'm happy to answer any you might have. Thanks for contributing!

**Comment by bohan-zhang** [comment]
@hartikainen Thank you so much for the pointers! I'll get started on Jan 1 and I will reach out if I have any questions!

**Comment by hartikainen** [comment]
This is closed by #23.
