### ISSUE TITLE
Gaussian mixture policies

### ISSUE THREAD

**Issue by seann999** [rail-berkeley/softlearning#30]
Are GMM policies stable with the Q-only formulation (without V function)? I see that this repository doesn't contain GMM policies while the old one (haarnoja/sac) does.
I am trying to get it working on rlkit but it seems like GMM policies are difficult to train without the V function.

**Comment by haarnoja** [comment]
Thanks for reporting this. In fact we were not aware that GMM policies are not stable without an explicit value function. The original SAC used GMMs, and at the time we noticed that using a value function made things a bit more stable, but after introducing several modifications and improvements (Gaussian policy, reparameterization trick, two Q-functions), we did not see any noticeable difference and thus eliminated the value function to make the algorithm simpler.  My guess is that that has something to do with the use of reparameterization trick, which we did not implement for the GMM policies. You migh want to try it out, or then just use separate value function.
