### ISSUE TITLE
Conda issues installing patchelf

### ISSUE THREAD

**Issue by BruceK4t1qbit** [rail-berkeley/softlearning#32]
I'll try to find a work-around.  Here's the output.  Thanks!

11:04:39 ~/git_repos/softlearning:master
  $ conda env create -f environment.yml
Solving environment: failed

ResolvePackageNotFound: 
  - patchelf=0.9

**Comment by hartikainen** [comment]
Can you try commenting out the [pathelf line in environment.yml](https://github.com/rail-berkeley/softlearning/commit/cc9f79e4691fb57fdfbc86f931dc58d2ed4ec294#diff-b7cb75ca59993a879e29bed8cd8469b8R9)?

**Comment by hartikainen** [comment]
We're mostly running things on ubuntu, but apart from the patchelf issue, things should work on osx as well. What's the error you're getting from numpy? Are you installing with conda?

**Comment by BruceK4t1qbit** [comment]
The numpy error was related to my bash aliases.  

And the limit.h header missing issue was resolved as described here:
https://github.com/rail-berkeley/softlearning/issues/33

**Comment by hartikainen** [comment]
@bohan-zhang added a comment for the patchelf line in environment.yml (https://github.com/rail-berkeley/softlearning/commit/e21db5335d1a262c383f7358d194b9918a023c2c#diff-b7cb75ca59993a879e29bed8cd8469b8R9). Hopefully that makes things a bit clearer.
