### ISSUE TITLE
Conda Issues installing on macOS 10.14 Mojave,

### ISSUE THREAD

**Issue by BruceK4t1qbit** [rail-berkeley/softlearning#33]
Here's what I found was needed to get this repo working on macOS 10.14 Mojave:

1) Comment out the following line in environment.yml:
- patchelf=0.9

2) Re-install .h files that were removed by the update to macOS 10.14 Mojave, following this answer:
https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave
  ->  Before I did this pip couldn't find the limit.h header file

**Comment by hartikainen** [comment]
Hey @BruceK4t1qbit, thanks a lot for reporting this! It's very useful. Let us know if you see any other issues.
