### ISSUE TITLE
Typo in refactoring flexible replay pool field logic

### ISSUE THREAD

**Issue by mihaic** [rail-berkeley/softlearning#39]
I think the following line should be:
```for field_name, field_attrs in fields_attrs.items():```
https://github.com/rail-berkeley/softlearning/blob/f569ec4ef746806a768d6ce802e9d9d8b6403fbc/softlearning/replay_pools/flexible_replay_pool.py#L36

**Comment by hartikainen** [comment]
You're absolutely correct. Somewhat luckily this has not caused any problems, and it's actually a bit difficult to come up with a failing test case for this. I'll get this fixed in a moment. Thanks a lot for reporting it!
