### ISSUE TITLE
self._Serializable__initialize(locals())  missing.      serializable package missing

### ISSUE THREAD

**Issue by garymcintire** [rail-berkeley/softlearning#4]
Trying to install...

I seem to be stuck because self._Serializable__initialize does not exist. I believe it is because the serializable package does not exist. And... much google searching doesn't turn it up either.
git+https://github.com/hartikainen/serializable.git@76516385a3a716ed4a2a9ad877e2d5cbcf18d4e6  in the requirements.txt file does not install and doesn't seem to exist anywhere on the web

Where can I get it???

**Comment by hartikainen** [comment]
Hey @garymcintire. It does install correctly on my machines, both on ubuntu and macos. How are you installing things?

The particular file refers to this commit: 
https://github.com/hartikainen/serializable/commit/76516385a3a716ed4a2a9ad877e2d5cbcf18d4e6

**Comment by garymcintire** [comment]
Yes. That is exactly the file I needed! I could not install it from the requirements file. I still cannot google it.

Thanks for showing it to me and thanks for being so quick to respond :)

**Comment by hartikainen** [comment]
Glad that it worked. What error does the pip install give you?

**Comment by garymcintire** [comment]
Well, I am installing differently. I tried to install as described with...
cd ${SOFTLEARNING_PATH}
conda env create -f environment.yml
conda activate softlearning

But I noticed that it installed everything in my prior environment, not in the softlearning env. Given that, I just continued on in my environment. My issues were that my mujoco license expired a couple years ago and I see no need to buy another now that Roboschool/pybullet exist.

**Comment by hartikainen** [comment]
I see. Yeah, the environment won't install without mujoco unfortunately. It's very unfortunate that you have to buy a license for it, but we haven't figured out any better alternative yet.

I'll close this issue as you seem to have figured out the problem. Feel free to reopen or open another one if problems persist.
