### ISSUE TITLE
No module named examples.development.simulate_policy

### ISSUE THREAD

**Issue by ycps** [rail-berkeley/softlearning#6]
In the [README.md](https://github.com/rail-berkeley/softlearning/blob/master/README.md), the following command is mentioned in order to simulate the resulting policy:
`python -m examples.development.simulate_policy […]`
However, I could not find this module in the [development](https://github.com/rail-berkeley/softlearning/tree/master/examples/development) directory.
When trying to run, python outputs the following error:
`/home/user/miniconda3/envs/softlearning/bin/python: No module named examples.development.simulate_policy`

**Comment by hartikainen** [comment]
Thanks for opening this. I forgot to add the `simulate_policy.py`. #7 addresses this.
