### ISSUE TITLE
How to set random seed?

### ISSUE THREAD

**Issue by quanvuong** [rail-berkeley/softlearning#61]
Thanks for the repo! 

How can I set the random seed for a run? There doesn’t seem to be an option to set the seed using command line arguments.

**Comment by hartikainen** [comment]
Currently the seed is hard coded in the variants. You can change it here:
https://github.com/rail-berkeley/softlearning/blob/1f6147c83b82b376ceed5e95df5a422113741468/examples/development/variants.py#L261

That seed is then fed to this function:
https://github.com/rail-berkeley/softlearning/blob/1f6147c83b82b376ceed5e95df5a422113741468/softlearning/misc/utils.py#L39
