### ISSUE TITLE
Union pool

### ISSUE THREAD

**Issue by tianheyu927** [rail-berkeley/softlearning#62]
Hi,

Seems like the [union pool](https://github.com/rail-berkeley/softlearning/blob/master/softlearning/replay_pools/union_pool.py) implementation is unfinished. Is that going to be done soon?

Thanks!

**Comment by hartikainen** [comment]
The `NotImplementedError`s don't actually mean that the pool is unfinished but that the implementation assumes that those functions are used via the pools that are unioned.

That said, we don't actually use the union pool anywhere anymore (within this repository), and it's very much possible that the union pool does not fully work out of the box. What's your use case for it? I probably don't have time to look further into fixing it anytime soon, but I would be happy to help you if you want to contribute a fix for it.
