### ISSUE TITLE
Module 'gym' has no attribute 'register' on MacOS Mojave 10.14.4

### ISSUE THREAD

**Issue by weijiafeng** [rail-berkeley/softlearning#88]
Hi All, when I tried to run a reward learning task (https://github.com/avisingh599/reward-learning-rl) with softlearning environment, the following error occurred: "**AttributeError: module 'gym' has no attribute 'register**'"  

However when I ran import gym and gym.register() on a separate python script on Pycharm it works fine, e.g. able to find the register module in gym. I had a look at the previous issues posted for Softlearning and think this is a gym adapter issue? But I am not sure how to manually add this environment/task onto gym_adapter in the Softlearning package? Many thanks for your help!!

<img width="920" alt="image" src="https://user-images.githubusercontent.com/40955107/58860161-17b35080-86de-11e9-854b-a3de29bd7da7.png">

**Comment by hartikainen** [comment]
It sounds like some other module named `gym` is colliding with the actual expected `gym`. Could you try seting a breakpoint (`import pdb; pdb.set_trace()`) in `softlearning/environments/gym/__init__.py` line 115, and calling `print(gym)`. What's the output of that?

Most likely the output is not the actual gym but some other module. Then what you would need to do is to find where that module gets imported. Could be that you manually have set something in your `PATH` or `PYTHONPATH` environment variable, or possibly your IDE loads it from somewhere.

Let me know if that helps or if you have any further questions.

**Comment by weijiafeng** [comment]
@hartikainen Hi Kristian, thanks for your reply!

I've ran that and the output is: **<module 'gym' from '/usr/local/lib/python3.7/site-packages/gym/__init__.py'>**. Is this the right gym package that it is using?  Thanks~

<img width="922" alt="image" src="https://user-images.githubusercontent.com/40955107/58868605-4128a800-86ef-11e9-8386-24f941fc9435.png">

**Comment by weijiafeng** [comment]
@hartikainen Any thoughts on my post above about the gym module path root? Thanks!

**Comment by hartikainen** [comment]
@weijiafeng That looks like it could be the right one. Now that I look at the gym code, it actually seems like the register at the top-level of gym is somewhat recently added: https://github.com/openai/gym/commit/812c46cbadfffedd5ee024379ff9d7a5673ff474#diff-9c9bed4efd3db64376fabec6bfd32891R11.

What if you changed that line to `gym.envs.make`, does that work?

**Comment by weijiafeng** [comment]
@hartikainen change which line to gym.envs.make?

**Comment by weijiafeng** [comment]
@hartikainen I managed to solve this by changing **gym.register** to **gym.envs.register**, but other error are popping up. I am tackling other errors now. Will raise another issue if needed. Thanks!

**Comment by hartikainen** [comment]
Happy to help. I'll close this for now, let me know if you any other issues pop up. Btw, the fact that `gym.register` is not defined suggests that you might want to upgrade your gym version 🙂

**Comment by avisingh599** [comment]
Thanks a lot Kristian!
