### ISSUE TITLE
Simulate policy not working anymore

### ISSUE THREAD

**Issue by kapsl** [rail-berkeley/softlearning#90]
In simulate_policy.py I had to replace
render_kwargs={'mode': args.render_mode}
on line 70

and in base_policy.py line 83 replaced it to
super(LatentSpacePolicy, self).__init__(kwargs['observation_keys'])

**Comment by hartikainen** [comment]
Hey @kapsl, thanks opening the issue! This was an oversight on my end, as I forgot to update the `simulate_policy.py` after the latest refactor. I'll get it fixed in the next PR.
