### ISSUE TITLE
git.exc.InvalidGitRepositoryError for GitPython v2.1.11 when running Softlearning environment

### ISSUE THREAD

**Issue by weijiafeng** [rail-berkeley/softlearning#93]
Hi Kristian, 

I've ran into a **git.exc.InvalidGitRepositoryError**: /Users/maggiefeng/reward-learning-rl/softlearning, in which the Git repo creation comes from the Softlearning utils.py file:
 "**/Users/maggiefeng/reward-learning-rl/softlearning/misc/utils.py", line 128, in get_git_rev
    repo = git.Repo('{}/..'.format(path))**"

 I've tried various methods as described in the GitPython GitHub Issues, however it still didn't work. And I am aware that this problem occurred in older versions of GitPython, but hasn't been raised much in last two years since the newer GitPython version came out. Yet I have installed the latest GitPython v2.1.11 and this issue still occurred. I am not sure if this is a GitPython problem or Softlearning environment problem - so I posted this issue in both packages' GitHub sites. Many thanks for your help!

<img width="937" alt="image" src="https://user-images.githubusercontent.com/40955107/59114081-f752f280-8978-11e9-813a-f21c8f7fab50.png">

**Comment by hartikainen** [comment]
Hei @weijiafeng, thanks for reporting this! Just to make sure, could you post the outputs similar to what I mention here: https://github.com/rail-berkeley/softlearning/issues/89#issuecomment-499333695. Assuming that those come out correctly, I don't really have ideas of how to debug this further.

If there's a way for you to provide a minimal failing example that I can reproduce on my end, I'd be happy to dive into it further.

**Comment by weijiafeng** [comment]
Hi Kristian, 

I followed your step in #89 to check for the .git repo at the root directory: 1) there is no .git in "**/Users/maggiefeng/reward-learning-rl/softlearning**"; but 2) there is .git one level up the folder in:"/Users/maggiefeng/reward-learning-rl". I git cloned it using "git clone https://github.com/avisingh599/reward-learning-rl.git". 

Hence my question is shall I add a .git in /Users/maggiefeng/reward-learning-rl/softlearning? or is this something to ask the author of reward-learning-rl @avisingh599 ? The softlearning folder in reward-learning-rl is the subfolder of softlearning master/softlearning on your GitHub. 

<img width="654" alt="image" src="https://user-images.githubusercontent.com/40955107/59142019-cb238a00-89e9-11e9-9ba1-73c82aa25ba2.png">

**Comment by hartikainen** [comment]
> 1) there is no .git in "/Users/maggiefeng/reward-learning-rl/softlearning";

This is fine. I think gitpython should be able to traverse up in the tree to find the `.git` inside the `/Users/maggiefengreward-learning-rl` folder. This requires that the `search_parent_directories=True` in the `get_git_rev` function here: https://github.com/rail-berkeley/softlearning/blob/master/softlearning/misc/utils.py#L106. Can you make sure that that's the case.

> Hence my question is shall I add a .git in /Users/maggiefeng/reward-learning-rl/softlearning? or is this something to ask the author of reward-learning-rl @avisingh599 ?

No, I think this is an issue somewhere else. Your setup seems to be as expected.

@avisingh599 Have you ever seen this issue?

**Comment by avisingh599** [comment]
Hmm, I have never seen this issue either. Is this part of the code used for obtaining the gitsha for logging?
